# Stock Price Prediction Using Linear Regression

### Importing Required Libraries

In [13]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

### Loading Data

In [50]:
data = pd.read_csv("/kaggle/input/2023-paytm/Quote-Equity-PAYTM-EQ-18-11-2022-to-18-11-2023.csv")
data1= pd.read_csv("/kaggle/input/tesla-latest-stock-data-2010-2020/TSLA.csv")

### Let's See The Data

In [55]:
data.head()
print("ajbdahbda")
data1.head()

ajbdahbda

         Date   Open   High    Low  Close  Adj Close    Volume
0  2010-06-30  5.158  6.084  4.660  4.766      4.766  85935500
1  2010-07-01  5.000  5.184  4.054  4.392      4.392  41094000
2  2010-07-02  4.600  4.620  3.742  3.840      3.840  25699000
3  2010-07-06  4.000  4.000  3.166  3.222      3.222  34334500
4  2010-07-07  3.280  3.326  2.996  3.160      3.160  34608500

In [56]:
data.info()
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           249 non-null    object
 1   series         249 non-null    object
 2   OPEN           249 non-null    float64
 3   HIGH           249 non-null    float64
 4   LOW            249 non-null    float64
 5   PREV. CLOSE    249 non-null    float64
 6   ltp            249 non-null    float64
 7   close          249 non-null    float64
 8   vwap           249 non-null    float64
 9   52W H          249 non-null    object
 10  52W L          249 non-null    float64
 11  VOLUME         249 non-null    object
 12  VALUE          249 non-null    object
 13  No of trades   249 non-null    object
dtypes: float64(8), object(6)
memory usage: 27.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2579 entries, 0 to 2578
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       2579 non-null   object
 1   Open       2579 non-null   float64
 2   High       2579 non-null   float64
 3   Low        2579 non-null   float64
 4   Close      2579 non-null   float64
 5   Adj Close  2579 non-null   float64
 6   Volume     2579 non-null   int64
dtypes: float64(5), int64(1), object(1)
memory usage: 141.2+ KB

In [60]:
data.describe()

,OPEN,HIGH,LOW,PREV. CLOSE,ltp,close,vwap,52W L
count,249.000000,249.000000,249.000000,249.000000,249.000000,249.000000,249.000000,249.000000
mean,722.683133,735.084137,709.435542,719.593976,720.504618,720.993976,722.160161,439.070281
std,147.671945,148.631227,145.151500,147.591037,147.258333,147.532035,146.765716,6.793320
min,444.000000,467.000000,438.350000,441.100000,441.150000,441.100000,452.310000,438.350000
25%,586.850000,605.400000,575.800000,580.750000,582.800000,583.900000,593.310000,438.350000
50%,710.700000,723.000000,701.500000,708.550000,709.700000,709.550000,712.320000,438.350000
75%,860.000000,871.450000,850.000000,857.350000,857.500000,857.400000,856.670000,438.350000
max,987.000000,998.300000,961.900000,987.650000,980.050000,987.650000,983.390000,510.050000

In [61]:
data1.describe()

,Open,High,Low,Close,Adj Close,Volume
count,2579.000000,2579.000000,2579.000000,2579.000000,2579.000000,2.579000e+03
mean,49.206686,50.301806,48.073117,49.253279,49.253279,3.078217e+07
std,57.934102,59.888383,55.852349,58.119783,58.119783,2.855717e+07
min,3.228000,3.326000,2.996000,3.160000,3.160000,5.925000e+05
25%,7.159000,7.268000,6.989000,7.153000,7.153000,1.047400e+07
50%,44.001999,44.660000,43.301998,43.924000,43.924000,2.413100e+07
75%,59.339000,60.171000,57.841000,59.020001,59.020001,3.979150e+07
max,502.140015,502.489990,470.510010,498.320007,498.320007,3.046940e+08

In [38]:
print(data.head())

         Date  series    OPEN    HIGH    LOW   PREV. CLOSE    ltp   close   \
0  17-Nov-2023      EQ  892.95  893.30  870.9        905.35  887.0  888.40
1  16-Nov-2023      EQ  920.00  922.85  898.0        919.10  904.0  905.35
2  15-Nov-2023      EQ  915.00  924.95  903.9        894.65  914.8  919.10
3  13-Nov-2023      EQ  891.00  899.00  891.0        894.80  894.7  894.65
4  12-Nov-2023      EQ  902.00  905.00  888.7        894.15  889.8  894.80

    vwap   52W H   52W L     VOLUME              VALUE  No of trades
0  883.18  998.30  438.35  55,42,250  4,89,48,20,843.55      1,76,622
1  909.96  998.30  438.35  27,98,897  2,54,68,91,970.25        73,431
2  913.82  998.30  438.35  38,02,638  3,47,49,39,055.50      1,06,542
3  894.88  998.30  438.35   8,60,179    76,97,60,712.75        36,558
4  896.93  998.30  438.35   3,23,914    29,05,28,326.30        10,408

In [63]:
x=data1[['High', 'Low', 'Open']].values

In [76]:
data.head()

,Date,series,OPEN,HIGH,LOW,PREV. CLOSE,ltp,close,vwap,52W H,52W L,VOLUME,VALUE,No of trades
0,17-Nov-2023,EQ,892.95,893.30,870.9,905.35,887.0,888.40,883.18,998.30,438.35,"55,42,250","4,89,48,20,843.55","1,76,622"
1,16-Nov-2023,EQ,920.00,922.85,898.0,919.10,904.0,905.35,909.96,998.30,438.35,"27,98,897","2,54,68,91,970.25","73,431"
2,15-Nov-2023,EQ,915.00,924.95,903.9,894.65,914.8,919.10,913.82,998.30,438.35,"38,02,638","3,47,49,39,055.50","1,06,542"
3,13-Nov-2023,EQ,891.00,899.00,891.0,894.80,894.7,894.65,894.88,998.30,438.35,"8,60,179","76,97,60,712.75","36,558"
4,12-Nov-2023,EQ,902.00,905.00,888.7,894.15,889.8,894.80,896.93,998.30,438.35,"3,23,914","29,05,28,326.30","10,408"

In [80]:
# X_paytm = data[['OPEN', 'HIGH', 'LOW']].values
print(data.index)
# X_paytm = data[['HIGH', 'LOW', 'OPEN']].values
# y_paytm = data['close'].values

RangeIndex(start=0, stop=249, step=1)

In [48]:
import pandas as pd
print(data.info())



X_paytm = data[['HIGH', 'LOW', 'OPEN']].values
y_paytm = data['close'].values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           249 non-null    object
 1   series         249 non-null    object
 2   OPEN           249 non-null    float64
 3   HIGH           249 non-null    float64
 4   LOW            249 non-null    float64
 5   PREV. CLOSE    249 non-null    float64
 6   ltp            249 non-null    float64
 7   close          249 non-null    float64
 8   vwap           249 non-null    float64
 9   52W H          249 non-null    object
 10  52W L          249 non-null    float64
 11  VOLUME         249 non-null    object
 12  VALUE          249 non-null    object
 13  No of trades   249 non-null    object
dtypes: float64(8), object(6)
memory usage: 27.4+ KB
None

KeyError: "None of [Index(['HIGH', 'LOW', 'OPEN'], dtype='object')] are in the [columns]"

### Separate the Input and Output Columns

In [39]:
X = data[['HIGH','LOW','OPEN']].values
y = data['close'].values

KeyError: "None of [Index(['HIGH', 'LOW', 'OPEN'], dtype='object')] are in the [columns]"

In [19]:
X

NameError: name 'X' is not defined

In [ ]:
y

### Spliting the Train and Test data

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=1)

NameError: name 'X' is not defined

### Linear Regression Model

In [21]:
regressor = LinearRegression()

### Fitting the data in the Model

In [22]:
regressor.fit(X_train, y_train)

NameError: name 'X_train' is not defined

In [23]:
print(regressor.coef_)

AttributeError: 'LinearRegression' object has no attribute 'coef_'

In [ ]:
print(regressor.intercept_)

### Prediction

In [24]:
predicted = regressor.predict(X_test)

NameError: name 'X_test' is not defined

In [ ]:
print(predicted)

### Combine the Actual and Predicted data

In [ ]:
data1 = pd.DataFrame({'Actual': y_test.flatten(), 'Predicted' : predicted.flatten()})

In [25]:
data1.head(20)

NameError: name 'data1' is not defined

### Mean Absolute Error

In [26]:
import math
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test,predicted))
print('Mean Squared Error:', metrics.mean_squared_error(y_test,predicted))
print('Root Mean Squared Error:', math.sqrt(metrics.mean_squared_error(y_test,predicted)))

NameError: name 'y_test' is not defined

### Plotting Graph

In [ ]:
graph = data1.head(20)

In [ ]:
graph.plot(kind='bar')

#### I hope you liked my notebook.